name: ecsim
channels:
  - conda-forge
dependencies:
  - astropy
  - jupyter
  - jupytext
  - matplotlib
  - numpy==2.1.3
  - pip
  - pytest
  - python==3.12
  - pyvista
  - scipy
  - tqdm
  - pip:
    - ngsolve==6.2.2406
    - webgui_jupyter_widgets
    - -e .
