name: ecsim
channels:
  - conda-forge
dependencies:
  - python ==3.10
  - numpy
  - scipy
  - matplotlib
  - tqdm
  - jupyter
  - jupytext
  - astropy
  - pip
  - pip:
    - ngsolve
    - webgui_jupyter_widgets
